#!/usr/bin/env python3
"""Emit a C++ corpus replay harness from fuzz_corpus_manifest.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any, Sequence


DEFAULT_MANIFEST = Path("fuzz_corpus_manifest.json")
DEFAULT_OUTPUT = Path("target/fuzz_corpus_replay/main.cc")


def _seed_bytes(seed: dict[str, Any]) -> bytes:
    if "text" in seed:
        return seed["text"].encode("utf-8")
    return bytes.fromhex(seed["hex"])


def _byte_array(data: bytes) -> str:
    if not data:
        return "0x00"
    return ", ".join(f"0x{byte:02x}" for byte in data)


def _escape_cpp_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )


def emit_replay_source(manifest_path: Path) -> str:
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    seed_arrays: list[str] = []
    seed_entries: list[str] = []
    seed_index = 0
    for component in payload["components"]:
        component_name = component["name"]
        for seed in component["seeds"]:
            symbol = f"kSeed{seed_index}"
            data = _seed_bytes(seed)
            seed_arrays.append(
                f"static const uint8_t {symbol}[] = {{{_byte_array(data)}}};"
            )
            seed_entries.append(
                "    {"
                f"\"{_escape_cpp_string(component_name)}\", "
                f"\"{_escape_cpp_string(seed['category'])}\", "
                f"\"{_escape_cpp_string(seed['name'])}\", "
                f"{symbol}, {len(data)}"
                "},"
            )
            seed_index += 1

    arrays = "\n".join(seed_arrays)
    entries = "\n".join(seed_entries)
    return f"""// Generated by tools/emit_fuzz_corpus_replay.py. Do not edit.
#include <cstdint>
#include <cstring>
#include <iostream>
#include <string_view>

#include "cpp/http_header_scanner_adapter.h"
#include "cpp/url_canonicalizer_adapter.h"
#include "cpp/mojo_validator_adapter.h"

namespace {{

struct Seed {{
  const char* component;
  const char* category;
  const char* name;
  const uint8_t* data;
  size_t len;
}};

{arrays}

static const Seed kSeeds[] = {{
{entries}
}};

bool SameView(std::string_view left, std::string_view right) {{
  if (left.size() != right.size()) {{
    return false;
  }}
  return left.empty() || std::memcmp(left.data(), right.data(), left.size()) == 0;
}}

bool ReplayHttpSeed(const Seed& seed) {{
  using namespace chromium_rust_perf;
  HttpHeaderScanOptions options{{1024, 8192}};
  HttpHeaderScanner scanner(options);

  HttpHeaderScanner::SetRollbackEnabled(false);
  HttpHeaderScanResult rust = scanner.Scan(seed.data, seed.len);
  HttpHeaderScanner::SetRollbackEnabled(true);
  HttpHeaderScanResult cpp = scanner.Scan(seed.data, seed.len);
  HttpHeaderScanner::SetRollbackEnabled(false);

  return rust.status == cpp.status &&
         rust.line_count == cpp.line_count &&
         rust.max_line_length == cpp.max_line_length &&
         rust.header_end_offset == cpp.header_end_offset;
}}

bool ReplayUrlSeed(const Seed& seed) {{
  using namespace chromium_rust_perf;
  UrlScanner scanner;

  UrlScanner::SetRollbackEnabled(false);
  UrlScanResult rust = scanner.Scan(seed.data, seed.len);
  UrlScanner::SetRollbackEnabled(true);
  UrlScanResult cpp = scanner.Scan(seed.data, seed.len);
  UrlScanner::SetRollbackEnabled(false);

  if (rust.status != cpp.status || rust.port != cpp.port) {{
    return false;
  }}
  if (rust.status != UrlScanStatus::kOk) {{
    return true;
  }}
  return SameView(rust.scheme, cpp.scheme) &&
         SameView(rust.username, cpp.username) &&
         SameView(rust.password, cpp.password) &&
         SameView(rust.host, cpp.host) &&
         SameView(rust.path, cpp.path) &&
         SameView(rust.query, cpp.query) &&
         SameView(rust.fragment, cpp.fragment);
}}

bool ReplayMojoSeed(const Seed& seed) {{
  using namespace chromium_rust_perf;
  MojoMessageValidator validator;
  MojoFieldConstraint fields[] = {{
      {{0, 4, 0}},
      {{4, 8, 1}},
  }};
  MojoMethodConstraint methods[] = {{
      {{100, 16, fields, 2}},
  }};
  MojoSchemaTable schema = {{methods, 1}};

  MojoMessageValidator::SetRollbackEnabled(false);
  MojoValidateResult rust = validator.Validate(seed.data, seed.len, &schema);
  MojoMessageValidator::SetRollbackEnabled(true);
  MojoValidateResult cpp = validator.Validate(seed.data, seed.len, &schema);
  MojoMessageValidator::SetRollbackEnabled(false);

  return rust.status == cpp.status && rust.error_offset == cpp.error_offset;
}}

bool ReplaySeed(const Seed& seed) {{
  if (std::strcmp(seed.component, "http_header_scanner") == 0) {{
    return ReplayHttpSeed(seed);
  }}
  if (std::strcmp(seed.component, "url_canonicalizer") == 0) {{
    return ReplayUrlSeed(seed);
  }}
  if (std::strcmp(seed.component, "mojo_validator") == 0) {{
    return ReplayMojoSeed(seed);
  }}
  std::cerr << "Unknown component: " << seed.component << std::endl;
  return false;
}}

}}  // namespace

int main() {{
  size_t failures = 0;
  for (const Seed& seed : kSeeds) {{
    if (!ReplaySeed(seed)) {{
      ++failures;
      std::cerr << "Corpus replay mismatch: " << seed.component << "/"
                << seed.category << "/" << seed.name << std::endl;
    }}
  }}
  if (failures != 0) {{
    std::cerr << "P0 fuzz corpus replay failed: " << failures
              << " mismatches." << std::endl;
    return 1;
  }}
  std::cout << "P0 fuzz corpus replay OK: " << (sizeof(kSeeds) / sizeof(kSeeds[0]))
            << " seeds." << std::endl;
  return 0;
}}
"""


def _parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args(argv)


def main(argv: Sequence[str]) -> int:
    args = _parse_args(argv)
    source = emit_replay_source(args.manifest)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8")
    print(f"Generated fuzz corpus replay harness: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
