#!/usr/bin/env python3
"""Emit a C++ rollback gate harness for P0 hot-leaf adapters."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Sequence


DEFAULT_OUTPUT = Path("target/rollback_gate/main.cc")


ROLLBACK_SOURCE = r"""// Generated by tools/emit_rollback_gate.py. Do not edit.
#include <cstdint>
#include <cstring>
#include <iostream>
#include <string_view>
#include <vector>

#include "cpp/http_header_scanner_adapter.h"
#include "cpp/url_canonicalizer_adapter.h"
#include "cpp/mojo_validator_adapter.h"
#include "cpp/css_tokenizer_adapter.h"

namespace {

bool SameView(std::string_view left, std::string_view right) {
  if (left.size() != right.size()) {
    return false;
  }
  return left.empty() || std::memcmp(left.data(), right.data(), left.size()) == 0;
}

bool TestHttpRollback() {
  using namespace chromium_rust_perf;
  const char* input = "Host: example.test\r\nConnection: close\r\n\r\n";
  const auto* data = reinterpret_cast<const uint8_t*>(input);
  const size_t len = std::strlen(input);
  HttpHeaderScanner scanner(HttpHeaderScanOptions{64, 1024});

  HttpHeaderScanner::SetRollbackEnabled(false);
  if (HttpHeaderScanner::IsRollbackEnabled()) {
    return false;
  }
  HttpHeaderScanResult rust_before = scanner.Scan(data, len);

  HttpHeaderScanner::SetRollbackEnabled(true);
  if (!HttpHeaderScanner::IsRollbackEnabled()) {
    return false;
  }
  HttpHeaderScanResult cpp = scanner.Scan(data, len);

  HttpHeaderScanner::SetRollbackEnabled(false);
  if (HttpHeaderScanner::IsRollbackEnabled()) {
    return false;
  }
  HttpHeaderScanResult rust_after = scanner.Scan(data, len);

  return rust_before.status == cpp.status &&
         rust_before.status == rust_after.status &&
         rust_before.line_count == cpp.line_count &&
         rust_before.line_count == rust_after.line_count &&
         rust_before.max_line_length == cpp.max_line_length &&
         rust_before.max_line_length == rust_after.max_line_length &&
         rust_before.header_end_offset == cpp.header_end_offset &&
         rust_before.header_end_offset == rust_after.header_end_offset;
}

bool TestUrlRollback() {
  using namespace chromium_rust_perf;
  const char* input = "https://example.test:443/a/b?x=1#frag";
  const auto* data = reinterpret_cast<const uint8_t*>(input);
  const size_t len = std::strlen(input);
  UrlScanner scanner;

  UrlScanner::SetRollbackEnabled(false);
  if (UrlScanner::IsRollbackEnabled()) {
    return false;
  }
  UrlScanResult rust_before = scanner.Scan(data, len);

  UrlScanner::SetRollbackEnabled(true);
  if (!UrlScanner::IsRollbackEnabled()) {
    return false;
  }
  UrlScanResult cpp = scanner.Scan(data, len);

  UrlScanner::SetRollbackEnabled(false);
  if (UrlScanner::IsRollbackEnabled()) {
    return false;
  }
  UrlScanResult rust_after = scanner.Scan(data, len);

  return rust_before.status == cpp.status &&
         rust_before.status == rust_after.status &&
         rust_before.port == cpp.port &&
         rust_before.port == rust_after.port &&
         SameView(rust_before.scheme, cpp.scheme) &&
         SameView(rust_before.scheme, rust_after.scheme) &&
         SameView(rust_before.host, cpp.host) &&
         SameView(rust_before.host, rust_after.host) &&
         SameView(rust_before.path, cpp.path) &&
         SameView(rust_before.path, rust_after.path) &&
         SameView(rust_before.query, cpp.query) &&
         SameView(rust_before.query, rust_after.query) &&
         SameView(rust_before.fragment, cpp.fragment) &&
         SameView(rust_before.fragment, rust_after.fragment);
}

bool TestCssRollback() {
  using namespace chromium_rust_perf;
  const char* input = ".box { color: red; content: \"abc\"; }";
  const auto* data = reinterpret_cast<const uint8_t*>(input);
  const size_t len = std::strlen(input);
  CssTokenizer tokenizer(CssTokenizeOptions{64, 256});

  CssTokenizer::SetRollbackEnabled(false);
  if (CssTokenizer::IsRollbackEnabled()) {
    return false;
  }
  CssTokenizeResult rust_before = tokenizer.Tokenize(data, len);

  CssTokenizer::SetRollbackEnabled(true);
  if (!CssTokenizer::IsRollbackEnabled()) {
    return false;
  }
  CssTokenizeResult cpp = tokenizer.Tokenize(data, len);

  CssTokenizer::SetRollbackEnabled(false);
  if (CssTokenizer::IsRollbackEnabled()) {
    return false;
  }
  CssTokenizeResult rust_after = tokenizer.Tokenize(data, len);

  return rust_before.status == cpp.status &&
         rust_before.status == rust_after.status &&
         rust_before.token_count == cpp.token_count &&
         rust_before.token_count == rust_after.token_count &&
         rust_before.max_token_length == cpp.max_token_length &&
         rust_before.max_token_length == rust_after.max_token_length &&
         rust_before.bytes_consumed == cpp.bytes_consumed &&
         rust_before.bytes_consumed == rust_after.bytes_consumed;
}

bool TestMojoRollback() {
  using namespace chromium_rust_perf;
  MojoMessageValidator validator;
  MojoFieldConstraint fields[] = {
      {0, 4, 0},
      {4, 8, 1},
  };
  MojoMethodConstraint methods[] = {
      {100, 16, fields, 2},
  };
  MojoSchemaTable schema = {methods, 1};

  std::vector<uint8_t> msg(40, 0);
  uint32_t header_size = 24;
  std::memcpy(&msg[0], &header_size, 4);
  uint32_t method_id = 100;
  std::memcpy(&msg[12], &method_id, 4);

  MojoMessageValidator::SetRollbackEnabled(false);
  if (MojoMessageValidator::IsRollbackEnabled()) {
    return false;
  }
  MojoValidateResult rust_before = validator.Validate(msg.data(), msg.size(), &schema);

  MojoMessageValidator::SetRollbackEnabled(true);
  if (!MojoMessageValidator::IsRollbackEnabled()) {
    return false;
  }
  MojoValidateResult cpp = validator.Validate(msg.data(), msg.size(), &schema);

  MojoMessageValidator::SetRollbackEnabled(false);
  if (MojoMessageValidator::IsRollbackEnabled()) {
    return false;
  }
  MojoValidateResult rust_after = validator.Validate(msg.data(), msg.size(), &schema);

  return rust_before.status == cpp.status &&
         rust_before.status == rust_after.status &&
         rust_before.error_offset == cpp.error_offset &&
         rust_before.error_offset == rust_after.error_offset;
}

}  // namespace

int main() {
  struct Case {
    const char* name;
    bool (*run)();
  };
  const Case cases[] = {
      {"http_header_scanner", TestHttpRollback},
      {"url_canonicalizer", TestUrlRollback},
      {"mojo_validator", TestMojoRollback},
      {"css_tokenizer", TestCssRollback},
  };

  size_t failures = 0;
  for (const Case& test : cases) {
    if (!test.run()) {
      ++failures;
      std::cerr << "Rollback gate failed: " << test.name << std::endl;
    }
  }
  if (failures != 0) {
    return 1;
  }
  std::cout << "P0 rollback gate OK: " << (sizeof(cases) / sizeof(cases[0]))
            << " components." << std::endl;
  return 0;
}
"""


def _parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args(argv)


def main(argv: Sequence[str]) -> int:
    args = _parse_args(argv)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(ROLLBACK_SOURCE, encoding="utf-8")
    print(f"Generated rollback gate harness: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
